### ISSUE TITLE
Reduce global state

### ISSUE THREAD

**Issue by Thalhammer** [mikke89/RmlUi#489] opened 2023-07-10 08:32 UTC
RmlUI should not depend on global state as heavily as it currently does.

I don't see a reason why
- SystemInterface
- RenderInterface
- FileInterface
- FontEngineInterface
- The Plugin registry

need to be global state. RenderInterface used to be per context and was moved to be global only with (as far as I can tell) no prior warning or hint about it to users, which caught them (or at least me) totally off guard.

The commit 0bbd019 that does so outlines the reasoning:
- **The feature added considerable complexity, since several types of render state needed to store their state per render interface.**
  This wouldn't be an issue if there would not be so much global state. Instead of removing the ability to use different interfaces, move the stuff that depends on the render interface into the context (or the render interface).

- **This complexity would have become more pronounced with upcoming changes for advanced render effects.**
  Not if it is contained in the scope it belongs to.
- **It was easy to make bugs where render resources (e.g. textures) would be freed in the wrong render interface.**
  Not if the render resources are stored where they belong (in the context that created them) instead of globally. How are you supposed to free a wrong resource if you don't even see it.
- **It was difficult to test for the presence of the above bugs.**
  Move the global stuff into the context and the above bugs are either gone (because you only see "your" data) or cause obvious compile errors.
- **No tests existed already, it is very likely that bugs were already present.**
  I have used multiple render interfaces for close to 3 months productive now and haven't hit a single one. So they either hide very well or there are no significant ones. But changing everything global wont make those bugs disappear, it just hides them better and makes them even harder to detect/debug.

I propose an alternative solution:
Remove all (most) of the global state and integrate it into the context and existing interfaces.
This gets rid of all the complexity mentioned above and makes RmlUI way more flexible with respect to using it in multiple windows/contexts from the same app (#407, #477, #480, #481, https://github.com/mikke89/RmlUi/issues/307#issuecomment-1520642302).

I'd be happy to help this conversion, as there is nothing else quite like RmlUI but I feel like instead of making it easier and more versatile to use, RmlUI goes the exact opposite way.

**Comment by mikke89** [comment] 2023-07-10 21:02
First of all, I am planning to reintroduce the per-context render interface with the upcoming effects branch. More of the render state has been collected into the context here, and perhaps we can make a better solution than previously. Users should expect several breaking changes as we are moving towards RmlUi 6.0, I'd recommend to stick with the releases for users that want stability.

Then, overall I agree with you, it would be good code hygiene to tie the interfaces to specific resources, the context in particular. What you are asking for is a lot of work though, and I need to make priorities. The previous solution was pretty much a glorified global, which is why I decided to remove it at the time.

If you are willing to help out, I'd be happy to see an effort into making this conversion. I will seriously consider such a change. Generally avoiding any breaking changes would be a priority.

**Comment by mikke89** [comment] 2023-07-11 16:14
Some breaking changes are acceptable, but try to keep it low when possible. Most of the new render interface features will be opt-in, although there will be a few breaking changes there.

Thanks for the kind words, and I'm certainly interested and looking forward to seeing how this turns out.

**Comment by mikke89** [comment] 2024-08-26 21:14
Cleaning up some old issues. For the RmlUi 6.0 release, the render interface is again tied to the context, which partly addresses the concern here. Since there hasn't been much activity on this issue I am closing this one, any further proposals for reducing the global state should be discussed in new issues or PRs.

**Closed by mikke89** 2024-08-26 21:14 UTC
Labels: enhancement, discussion

**Comment by dsp56300** [comment] 2025-08-12 19:53
Unfortunately this one is closed already, still wanted to give my 2ct here:

We use RmlUi for audio plugins. Audio plugins are shared libraries that are loaded into a runtime executable of some sort, a sequencer software for example.

The problem is that multiple instances of one plugin can be loaded and on windows machines, they share the same heap.

Every instance of a plugin can be loaded with a different configuration, including a skin. A skin includes fonts, obviously rcss/rml and lots of other stuff. Also, multiple instances of a plugin can be executed in different threads. For this to work, rmlui had to be reworked to be multi instance compatible.

We introduced a new class: **CoreInstance**. And this instance is forwarded to every static rmlui call. Honestly speaking though, this was quite a hassle to do as there are very many areas in rmlui that use statics for all sorts of stuff and there are areas in rmlui that need that coreinstance that you wouldn't expect. Some of them are:

* The TypeConverter API needs the CoreInstance because there are some converters that need the style sheet specification, which is now part of that CoreInstance. Coming along is that all Rml::Variant instances need the core instance too. 
* Also, the overwritten operators new/delete for layout boxes had to be removed as they access static allocation pools. Instead of using operator new, a Create() function has been introduced, needing the CoreInstance& reference.
* RML_ASSERT and similar macros do no longer call the system interface for now, because we din't want to pass the CoreInstance to every assert.

If there is really a larger interest to use this, checkout our fork. but be aware that there renderers need small changes too, this is not part of the repo because we use a custom one. But due to the massive rework need we didn't want to open a PR for now as it will most probably get rejected anyway. But we were in desperate need for a clean multi instance scenario so thats what we did.

**Comment by mikke89** [comment] 2025-08-16 17:57
@dsp56300 Thanks, it's interesting to hear how you've been working with the library, and the modifications you made. This is really a use case I have never considered. I can only imagine how many parts that would touch, we do use a lot of statics all over the place. If I rewrote everything from scratch I'd love to replace all of that with something more plug-able. But yeah, I just don't see us being able to invest in doing that right now, and the massive changes that would take, unfortunately.

I do wonder if you considered having a global lock around the UI parts, even if coming from multiple threads? Although I can see some reasons why that might not be satisfactory.

I do appreciate you sharing your work, I'll add the fork to the thirdparty resources so that others can more easily find it in the future too.

Also, I'd be interested to see what more you are doing with the library :)
