### ISSUE TITLE
Vulkan Backend does not work with Lottie animations over time

### ISSUE THREAD

**Issue by MarioSieg** [mikke89/RmlUi#610] opened 2024-04-18 15:53 UTC
When displaying an lottie animation with the Vulkan Backend, the descriptor set allocation fails after some frames because the lottie renderes creates a new texture every frame, but the VK backend never frees the associated descriptors.
Any workaround or fix?

**Comment by wh1t3lord** [comment] 2024-04-18 16:35
@MarioSieg Thanks for noticing, I will check and fix. 

But Vulkan is outdated for current release of library tbh. Better to wait some time for upcoming fixes. 

I dont want to recommend making any pr related to that thing because I will re-write some part of vulkan due to new features of library. Thanks for patience.

**Comment by MarioSieg** [comment] 2024-04-18 16:40
> @MarioSieg Thanks for noticing, I will check and fix.
> 
> But Vulkan is outdated for current release of library tbh. Better to wait some time for upcoming fixes.
> 
> I dont want to recommend making any pr related to that thing because I will re-write some part of vulkan due to new features of library. Thanks for patience.

Sounds good thanks.
It would also be great if the new Vulkan impl could work with existing renderers like (ImGui does): I pass my own created Device struct and my own CommandBuffer struct when calling Render() because there's a lot unused code for instance creation and a lot of changes needed to make it work with an already existing Vulkan renderer

**Comment by wh1t3lord** [comment] 2024-04-18 16:50
@MarioSieg Yeah I agree, that is what new features are about is to provide easy integration model for users and for their custom backends I discussed with mikke about that thing a long time ago.

**Comment by mikke89** [comment] 2024-04-21 14:01
@MarioSieg Which commit are you on?

I tried to run the lottie sample for a couple of hours, but I did not see any issues here. I could not replicate this. Also stepped through it in the debugger, and from first impressions it does look like the descriptors are released here.

**Comment by wh1t3lord** [comment] 2024-05-13 09:39
@MarioSieg ^^^^^

**Comment by MarioSieg** [comment] 2024-06-08 10:19
Hey sorry for the late reply. I cannot give and useful information further as we decided to move to Noesis GUI for the in game UI :/ maybe it was an issue on our side hard to tell but if it worked for you...

**Comment by mikke89** [comment] 2024-06-10 20:45
I understand. I am closing this as non-reproducible for now then. If anyone else can observe this problem then please go ahead and open a new issue.

**Closed by mikke89** 2024-06-10 20:45 UTC
Labels: backends
