### ISSUE TITLE
demo high cpu usage

### ISSUE THREAD

**Issue by hot202xu1** [mikke89/RmlUi#349] opened 2022-08-18 18:03 UTC
When trying out all the demos, in windows 11 i seem to be getting really high cpu usage.
is there anyway to have a wait for message or something in the loop?

**Comment by xland** [comment] 2022-08-19 00:29
See https://github.com/mikke89/RmlUi/discussions/331#discussioncomment-3030216

**Comment by hot202xu1** [comment] 2022-08-19 03:13
There cpu usage is like 1% it puts mine up to 16% like it would if in a game. I wanted to use this as a windows desktop application

**Comment by xland** [comment] 2022-08-19 06:46
Which backend do you use?
My backend is OpenGL.

**Comment by hot202xu1** [comment] 2022-08-19 07:48
I just built the example, I think it’s opengl

**Comment by mikke89** [comment] 2022-08-19 10:53
This is a duplicate of #331, please see the discussion there.

Otherwise, this is the responsibility of the user as they are in full control of their own main loop. The built-in samples don't do anything fancy here so CPU usage will be dominated by whether or not vsync is enabled in your GPU driver.

**Closed by mikke89** 2022-08-19 10:53 UTC
