### ISSUE TITLE
Get rid of RTTI

### ISSUE THREAD

**Issue by viciious** [mikke89/RmlUi#63] opened 2019-10-25 10:43 UTC
It'd be awesome of RmlUi didn't insist on being compiled with RTTI enabled. First and foremost, it would reduce the footprint of the library considerably. Second of all, this should reduce compilation time. And on top of that, it would make integrating the library into RTTI-less projects easier.

There are all kinds of RTTI and dynamic_cast replacements found on the Internet, however this particular one caught my attention: http://kahncode.com/2019/09/24/c-tricks-fast-rtti-and-dynamic-cast/

**Comment by andreasschultes** [comment] 2019-10-25 17:05
Maybe this branch is interesting for this
https://github.com/crazyjul/libRocket/tree/no_rtti

**Comment by mikke89** [comment] 2019-10-27 09:52
Thanks for the suggestion. I'm not sure I really like replacing language features with custom libraries. 

With that said, I think we only use dynamic_cast for down casting, and only for the extra safety it provides. Thus, a possible solution is to replace the dynamic_casts by static_casts for users that don't need or are willing to remove that extra layer of safety. But keep the dynamic_casts by default. What do you think?

**Comment by viciious** [comment] 2019-10-28 07:50
> With that said, I think we only use dynamic_cast for down casting, and only for the extra safety it provides. Thus, a possible solution is to replace the dynamic_casts by static_casts for users that don't need or are willing to remove that extra layer of safety. 

Hm.. I think having some form of dynamic casting is essential in case of plugins because they take pointers to the parent class in the installed hooks. In case your plugin instantiates objects that inherit from the base class, it needs to to downcast in the hook to be able to do something useful.

**Comment by mikke89** [comment] 2019-10-28 10:38
Down casting with static_cast is perfectly possible, but unsafe. The problem one may encounter is that the factory is set up wrong, so that a derived type is not returned when expected. Then you will have undefined behavior after performing static_cast and using the derived object.

Internally I have not encountered this issue (that would be a bug). Generally, I think it should be reasonable to enable this for users that are willing to trade the extra safety checks for performance.

**Comment by viciious** [comment] 2019-10-28 12:46
> Down casting with static_cast is perfectly possible, but unsafe.

That's exactly my point. See this `OnDocumentLoad` hook for instance:
https://github.com/Qfusion/qfusion/blob/master/source/ui/kernel/ui_rocketmodule.cpp#L308

This isn't going to play well/safe without dynamic_cast in case of Debugger documents, which clearly aren't instances of ASUI::UI_ScriptDocument at all.

**Comment by mikke89** [comment] 2019-10-28 16:53
@viciious I see, that is certainly a case where static_cast is not usable by itself. A possible workaround is to use a custom tag name or an attribute, although I understand the inconvenience caused by that.

However, the example implementation linked in the first post has limitations that are not acceptable for our library, in particular due to the type id not working across shared libraries. The complexity is also too high in my opinion. 

@andreasschultes Something along the lines of what you showed here would be more reasonable. Although, I am not sure whether or not this would work across shared libraries, maybe you have some insight here?

The simplest solution would be a virtual function that returns an enum with the element type, and we static_cast based on this. This solution is a bit error prone though, but at least very transparent.

**Comment by viciious** [comment] 2019-10-28 17:21
> The simplest solution would be a virtual function that returns an enum with the element type, and we static_cast based on this. This solution is a bit error prone though, but at least very transparent.

For this solution, I'd prefer the library to keep track of element classes and ids so you can upcast or downcast objects at will without having to do the typeswitching yourself. That would require having some kind of type id registry/mapping.

**Comment by andreasschultes** [comment] 2019-10-28 18:18
I think it should work across shared libraries, because the static variable in the classes has an unique memory address at runtime, so every class has one unique id based on the memory address. The rest is done by virtual functions.
I think a enum would be case the problem of probably conflicting ids, as already mention.

**Comment by viciious** [comment] 2019-10-29 07:45
> Another possibly safer approach is to use a compile time hash of the type name.

This seems like a good solution!

**Comment by mikke89** [comment] 2019-11-06 13:37
> Maybe this branch is interesting for this
> https://github.com/crazyjul/libRocket/tree/no_rtti
> or this merge commit
> [andreasschultes@b1a6695](https://github.com/andreasschultes/libRocket/commit/b1a66953ee9134ee8f1d8063c1c28337b974fc6e)

Started an implementation based on this in the no_rtti branch. It looks like it should work for shared libraries with the proper import/export specifications, at least my brief research into this suggests so.

We do see a nice little performance benefit as well when disabling rtti and exceptions. I'm not super happy about all the macros needed though.

The compile time hash I suggested earlier is problematic due to difference in spelling of the types, especially when considering namespaces. Thus, such a solution would need to specify both the type as well as some name for dynamic casts. Seems a bit error prone and not so pretty? Maybe there are smarter ways around it. I'd like to avoid all the macros though, so I'll think about this some more.

**Comment by mikke89** [comment] 2019-11-28 21:44
Merged into master, see 196039e2827cccc02cc564f7e8d011ab17937b78.

**Closed** 2019-11-29 18:08 UTC
Labels: enhancement
