### ISSUE TITLE
Error compiling RmlUI 5.1 with current version of MSYS2

### ISSUE THREAD

**Issue by barotto** [mikke89/RmlUi#555] opened 2023-12-27 17:52 UTC
Using the current version of the MSYS2 build environment on Windows (gcc 13.2.0), compilation of RmlUi 5.1 fails with the following error:
```
In file included from C:/workspace/RmlUi/Source/Core/ElementAnimation.cpp:40:
C:/workspace/RmlUi/Source/Core/ElementStyle.h:43:6: warning: elaborated-type-specifier for a scoped enum must not use the 'class' keyword
   43 | enum class PseudoClassState : std::uint8_t { Clear = 0, Set = 1, Override = 2 };
      | ~~~~ ^~~~~
      |      -----
C:/workspace/RmlUi/Source/Core/ElementStyle.h:43:12: error: use of enum 'PseudoClassState' without previous declaration
   43 | enum class PseudoClassState : std::uint8_t { Clear = 0, Set = 1, Override = 2 };
      |            ^~~~~~~~~~~~~~~~
```

This can be resolved including `cstdint` in `Include/RmlUi/Core/Types.h`:
```
#include <cstdint>
```

**Comment by mikke89** [comment] 2023-12-27 21:32
Hey, and thanks for reporting. This looks like a duplicate of #470 and #545, already fixed in `master` branch.

**Comment by barotto** [comment] 2023-12-28 08:40
Thanks, unfortunately I have to use 5.1 as `master` completely breaks my UI.

**Comment by mikke89** [comment] 2023-12-28 20:33
Yeah, there have been some layout changes. I hope it's not too much trouble to upgrade, let me know if I can help with that.

In any case, I'm closing this one. It should be possible to apply this patch to 5.1, at least manually: https://github.com/mikke89/RmlUi/commit/313cbab6570a45fba1a08534da7c3b46b812fa48

**Closed by mikke89** 2023-12-28 20:33 UTC
Labels: duplicate, build

**Comment by barotto** [comment] 2023-12-28 21:14
Thank you very much for the link to the patch.

Though CMake is already giving me deprecation warnings so I'm afraid I won't have a choice but to upgrade soon.
