### ISSUE TITLE
Assertion failure in EventDispatcher::TriggerEvents

### ISSUE THREAD

**Issue by viciious** [mikke89/RmlUi#45] opened 2019-09-01 17:42 UTC
The following line produces an assertion failure in debug build in MSVC:

```
	for (auto it = begin; it != end; ++it)
```

Further down the stack:
```
	_Vector_const_iterator& operator++()
		{	// preincrement
 #if _ITERATOR_DEBUG_LEVEL != 0
		const auto _Mycont = static_cast<const _Myvec *>(this->_Getcont());
		_STL_VERIFY(_Ptr, "can't increment value-initialized vector iterator");
		_STL_VERIFY(_Ptr < _Mycont->_Mylast, "can't increment vector iterator past end");
 #endif /* _ITERATOR_DEBUG_LEVEL != 0 */
```

The _Mycont pointer is null

**Comment by viciious** [comment] 2019-09-01 17:46
In this particular case, a button click closes the document which triggers another event.

**Comment by viciious** [comment] 2019-09-01 18:32
Changing the loop to read:
```
	for (auto it = begin, next = end; it != end; it = next)
	{
		next = std::next(it, 1);
		it->listener->ProcessEvent(event);
	}
```
fixes the assertion :)

**Comment by mikke89** [comment] 2019-09-01 22:28
Yeah, I think the problem is that when adding or removing listeners, the iterators will be invalidated. Could you test the changes I committed?
The commit should help avoid invalidated iterators, but may result in a skip or repeat of a listener invocation.

**Comment by viciious** [comment] 2019-09-02 13:38
I think the best solution here would be to copy the slice of the original array to a temporary array and iterate over that.

**Closed** 2019-09-13 13:32 UTC
