### ISSUE TITLE
Scrollable boxes don't reset their scrollable bounds when the content changes

### ISSUE THREAD

**Issue by Paril** [mikke89/RmlUi#672] opened 2024-09-16 23:19 UTC
This *may* have gotten fixed in 6.x but I haven't had the time to check yet, I wanted to make sure I noted this down because I'll forget otherwise.

If you fill a container with data such that you can scroll it, and you scroll the container by any amount, replacing the content in the scrollable area does not clamp the new allowable bounds and it will stay locked. Currently, our workaround is just to manually `ScrollTo({ 0, 0 })` when we update the element (which may be required anyways because we want to scroll back to the top), but I think most browsers clamp the scrollTop to the new allowable maximum instead of having stuff get rendered out of bounds.

**Comment by mikke89** [comment] 2024-09-24 20:44
I just tested this on the latest master, and I couldn't reproduce it. I tested by removing content when responding to a click event in the demo sample. Seemed to clamp the scroll offset to the (new) bottom as expected.

I am closing this as non-reproducible. If you manage to reproduce this on the latest master, please go ahead and open it again or post a new issue, with as many details as possible :) Cheers.

**Closed by mikke89** 2024-09-24 20:44 UTC
Labels: invalid
